# Generated by Django 2.2.27 on 2022-08-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartPageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_result', models.BooleanField()),
                ('second_result', models.BooleanField()),
                ('third_result', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_result', models.BooleanField()),
                ('second_result', models.BooleanField()),
                ('third_result', models.BooleanField()),
                ('start_page_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARPictureBook.StartPageResult')),
            ],
        ),
        migrations.CreateModel(
            name='SecondPageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_result', models.BooleanField()),
                ('second_result', models.BooleanField()),
                ('third_result', models.BooleanField()),
                ('start_page_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARPictureBook.StartPageResult')),
            ],
        ),
    ]
