# Generated by Django 2.2.27 on 2022-09-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARPictureBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroExpressionDetectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('question_num', models.IntegerField()),
                ('detection_result', models.CharField(max_length=255)),
                ('start_page_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARPictureBook.StartPageResult')),
            ],
        ),
        migrations.CreateModel(
            name='ActionDetectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('question_num', models.IntegerField()),
                ('detection_result', models.CharField(max_length=255)),
                ('start_page_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ARPictureBook.StartPageResult')),
            ],
        ),
    ]
