# Generated by Django 2.2.27 on 2022-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARPictureBook', '0004_auto_20220916_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswerinfo',
            name='running_mode',
            field=models.CharField(default='Testing', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerresult',
            name='action_detection_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answerresult',
            name='micro_expression_detection_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
