# Generated by Django 2.2.27 on 2022-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARPictureBook', '0005_auto_20220916_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerresult',
            name='question_result',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
