# Generated by Django 2.2.27 on 2022-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARPictureBook', '0008_finalresult_self_report_result_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalresult',
            name='micro_expression_detection_result',
        ),
        migrations.AddField(
            model_name='finalresult',
            name='anger_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='disgust_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='fear_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='happiness_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='neutral_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='sadness_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='surprise_prob',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
