# Generated by Django 2.2.27 on 2022-10-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARPictureBook', '0009_auto_20221008_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='anger_prob_imi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='disgust_prob_imi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='fear_prob_imi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='happiness_prob_imi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='neutral_prob_imi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='sadness_prob_imi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='surprise_prob_imi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
